apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: alexandrit
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJkbTk1ZEdWdWEyOTJRR2x1WW05NExuSjFPbWRvY0Y5MWQwbHJhRXhMVDBONFJVVnhiRUZzUkUxaU5HVTVVWFIwT1VwSFdsRXphMWszVFVJPSIKCQl9Cgl9LAoJImN1cnJlbnRDb250ZXh0IjogImRlc2t0b3AtbGludXgiCn0=
type: kubernetes.io/dockerconfigjson
